Repository FFXIV-CombatReborn/RotationSolverReborn, pull requests merged in 2024-07, with the labels that each got.

#251 Minor changes to Monk base rotation
  RotationSolver.Basic/Rotations/Basic/MonkRotation.cs
Labels: under review

#256 Remove restriction for Perfect Balance
  RotationSolver.Basic/Rotations/Basic/MonkRotation.cs
Labels: under review

#264 Added additional positional actions
  RotationSolver.Basic/Helpers/ConfigurationHelper.cs
Labels: enhancement, under review

#265 Fixed Reign Combo Part 2
  RotationSolver.Basic/Rotations/Basic/GunbreakerRotation.cs
Labels: good first issue

#293 Update AstrologianRotation.cs
  RotationSolver.Basic/Rotations/Basic/AstrologianRotation.cs
Labels: under review
